name=input("enter your name")
age=int(input("enter your age"))
marks=int(input("enter your marks"))
print("Name:",name)
print("Age:",age)
print("Marks:",marks)
print("Type of Name:", type(name))
print("Type of Age:", type(Age))
print("Type of Marks:", type(Marks))
